/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SUMA_STRUCT_H_RPCGEN
#define _SUMA_STRUCT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operandos {
	int primero;
	int segundo;
};
typedef struct operandos operandos;

#define CALC_PROG 0x20000199
#define CALC_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define suma 1
extern  int * suma_1(operandos *, CLIENT *);
extern  int * suma_1_svc(operandos *, struct svc_req *);
extern int calc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define suma 1
extern  int * suma_1();
extern  int * suma_1_svc();
extern int calc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operandos (XDR *, operandos*);

#else /* K&R C */
extern bool_t xdr_operandos ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SUMA_STRUCT_H_RPCGEN */
